### ISSUE TITLE
Gather suggestions Issus

### ISSUE THREAD

**Issue by ElevenFan** [alphaess-developer/alphacloud_open_api#10]
Hi All，This Issus mainly collects your suggestions on using Api. Currently, we are developing it from our own perspective. I hope you can put forward your own ideas, and I will try my best to realize it. Specifically, I don't know what you use Api to do.
Our German translation is still in progress, and the current German version uses English.
If you find a bug, you can mention it to me on Issus, and we will fix it as soon as we receive it.
We usually use slack to communicate。
Thanks~

**Comment by Gaspode69** [comment]
Hi @ElevenFan,

thank you so much for this API.

In my case, I want to use it to provide an integration into the home automation platform ioBroker. Basically, the integration in ioBroker delivers all values the API provides and allows to set values the API allows. The ioBroker users can then create their own dashboards/visualizations and use the values for controlling other home automation devices.

**currently, the following values are very popular:**
* power per string
* power per phase
* inverter Power, also per phase
* charging power of electric car
* statistical values like
 -- currency
 -- CO2 reduction today/total
 -- generation today/total
 -- charging energy of electric car
 -- income today/total
 -- self consumption today/total
 -- self sufficiency today/total
 -- plants planted today/total

**Comment by dehsgr** [comment]
Hi @ElevenFan,

As suggested in issue #1 the should be a way for fetching historical data for a specific time range (such as in the monitoring portal). It would be very helpful to get a monthly and yearly view on the data for being able to calculate and visualize curves (progress/history) for the specific value for one month or for one year.

**Comment by IAmKonni** [comment]
My wishes are:
- setting limits for charging and discharging power (e.g. up to maximum of 1 kW instead of 3 kW that are possible by the hardware)
- setting forced charging / discharging with a given power as well as forced "stop" (idle, don't charge or discharge, just hold the SoC)
- firmware version information
- details about battery information (temperature, cell voltages, etc.), separated by each battery device.

Additionally a web socket connection would be nice, so I can get the latest live updates immediately without explicit polling. Alternatively a MQTT protocol would be even nicer. 😊

**Comment by ElevenFan** [comment]
@dehsgr Our power map is beautified。Statistics can be added。

**Comment by ElevenFan** [comment]
@Gaspode69 can join。

**Comment by ElevenFan** [comment]
@IAmKonni This Api cannot be opened, and the Api that is forced to charge and discharge will cause problems for the device.

**Comment by IAmKonni** [comment]
I don't mean forced charging/discharging on a low technical level. I don't want to override the BMS or something similar. I just want some more possibilities to control charging and discharging according to my personal needs. For example I want to reduce discharge power, when my heat pump heathens the water, so that the battery does not fully discharge.
I have some more use cases with my wallboxes and electric cars.

**Comment by RizzoRat** [comment]
I go with Gaspode, I'd love to see  string current and voltage data, at least for live view.

I suggest to add EMS status to getLastPowerData data

**Comment by adriaanwebb** [comment]
Hi @ElevenFan,  Great work on opening the API up.

Would be great to get the current status of the GRID power status if it is On or Of.  Knowing the current GRID status can be used in many home automation actions, like switching the geyser off should the GRID be off and battery gets to certain low percentage.

**Comment by dehsgr** [comment]
> @dehsgr Our power map is beautified。Statistics can be added。

@ElevenFan thank you very much for all the work you did until yet!

The new open API looks great and I took first steps for integrating it into [my project](https://github.com/dehsgr/node-red-contrib-alphaess). Do you have any roadmap for upcoming features? Historical data are prerequisite for me for being able to switch over my project to open API. I would be very happy for being able to switch over soon after release.

**Comment by RizzoRat** [comment]
Maybe it's also a good idea to have a method to read modbus registers (that way you can provide a lot of status data with a single method). However, it's clear this can only be delayed live data. For those delays, I think I would not allow writing to registers, though.

**Comment by RizzoRat** [comment]
and aux contact configuration read and write maybe? Then the API would probably cover full web interface/App functionality (i think)

**Comment by RizzoRat** [comment]
Oh, and very important:
getLastPowerData should provide a (Unix-)timestamp when this data was created or received, so we can determine the age of the live view and detect when for example cases of the inverter losing WiFi/internet connectivity

**Comment by ElevenFan** [comment]
There are some Api control equipment, I suggest that you give feedback to the company's after-sales service in each country. If there are more people who give feedback, I can develop it when I receive the demand.This is address：https://www.alphaess.com/contact-us

**Comment by dehsgr** [comment]
So you wouldn‘t follow up the suggestions above? What was your intention opening up this issue then? 😳

**Comment by ElevenFan** [comment]
@dehsgr I need to know what Apis are still needed, because I don't know what you want the API to do.But there are also people monitoring me here, I hope everyone can give feedback。

**Comment by IAmKonni** [comment]
I renew my demand/wish for limiting the maximum charge/discharge power ... :)

**Comment by adriaanwebb** [comment]
@ElevenFan again here is my API request. This is something that will add value to your solution/APIs and the community to consume your product.

A great feature to add as a new response parameter from the Alpha ESS systems API would be to show the current status of the power GRID. This value should indicate if the GRID power status is currently ON or OFF.

Knowing the current GRID status can be used in many home automation actions and events, Like: switching high energy appliances off e.g. switching the Hot Water Geyser off should the GRID be OFF when the SOC battery gets to certain low percentage level.

Many other Invertor vendor has this status available already and it would be a welcome feature to support this as well.

**Comment by Gaspode69** [comment]
> A great feature to add as a new response parameter from the Alpha ESS systems API would be to show the current status of the power GRID.

I agree. The question is how reliable this would be because if the power grid is not available there is probably no more communication possible (in my case it is rather likely that the DSL infrastructure is down, too)

**Comment by ElevenFan** [comment]
@adriaanwebb our product manager ask me：What is the communication port between grid and storage to get the grid Status? And what is the communication port that storage Control the Home devices? Such as EVU, Modbus or AUX?

**Comment by adriaanwebb** [comment]
@ElevenFan my current setup at home it that I use Home Assistant with the unofficial https://github.com/CharlesGillanders/homeassistant-alphaESS HACS integration to monitor my Alpha ESS system. My home Hot Water Geyser has a Sonoff POW R3 25A 5500W Smart Switch that is also integrated into Home Assistant as well. If your Alpha ESS API will provide the current GRID Status it would be easy to do an automation using Home Assistant for example if the GRID == OFF and the ESS SOC goes < 60% to switch the Geyser off via the local LAN. I see the Home Assistant doing all the heavy work using other smart devices on the local LAN. Another nice feature I would to do is to send myself a notification when the GRID == OFF to all users who are at home so that they know that the power GRID is off. 

BTW - My internet connectivity is via Fibre (@Gaspode69 ) and is not impacted when the GRID is off.  Internet service continues as normal.

**Comment by ElevenFan** [comment]
@Gaspode69 Today I add new api,getSumDataForCustomer,you can try to test it.

**Comment by Gaspode69** [comment]
@ElevenFan 
> @Gaspode69 Today I add new api,getSumDataForCustomer,you can try to test it.

Works perfectly. Thank you! 

Now for me only the following items are missing, then the API would be perfect for me:
* power per string
* power per phase
* inverter power, also per phase
* charging power of electric car

**Comment by ElevenFan** [comment]
@dehsgr @adriaanwebb About this Api ，you can contact our German office for after-sales and give them a suggestion，TEL： +49 6103 4591 601，I can't make this decision with this Api。

**Comment by roggepaul** [comment]
I would also like to make a suggestion: since I want to change settings of a SMILE-EVCT11 Wallbox it would be nice if changing those settings via api and automate it would be possible instead of using the app all the time. I have not found any solution to change wallbox settings without using the mobile APP or the web app.

**Comment by ElevenFan** [comment]
@roggepaul  SMILE-EVCT11 is our EV-Charging，Do you have our EV-Charging？This feature is hardly noticed，So I want to know what you want to do with this API。

**Comment by roggepaul** [comment]
@ElevenFan yes, i own your wallbox and want to Switch between the three Eco charging modes. Activating and deactivating (like it is possible in the app) would also be a nice feature that would help me with my automation

**Comment by MrIcemanLE** [comment]
> I don't mean forced charging/discharging on a low technical level. I don't want to override the BMS or something similar. I just want some more possibilities to control charging and discharging according to my personal needs. For example I want to reduce discharge power, when my heat pump heatens the water, so that the battery does not fully discharge. I have some more use cases with my wallboxes and electric cars.

If you have a hourly payed price for electric home power (e.g. Tibber, AWATTAR, etc.), this feature would be great to use the power from the grid in cheap hours and save the battery for expensive hours
