### ISSUE TITLE
How to add up power numbers?

### ISSUE THREAD

**Issue by chrisgeli** [alphaess-developer/alphacloud_open_api#18]
I have created the following script, to compare a day's PV energy to the sum of the PV power numbers. Note that in order to run the script, you need to create a `credentials.py` defining the `SystemSN`, `AppID` and `AppSecret` values for your system.

```
import asyncio
from alpha_api_demo import (
    AlphaESSAPI,
)
import credentials
import time
import datetime

delta_seconds = lambda e1, e2 : (
    datetime.timedelta() 
    + datetime.datetime.fromisoformat(e2['uploadTime'])
    - datetime.datetime.fromisoformat(e1['uploadTime'])
).seconds

async def compareepv() -> None:
    ae = AlphaESSAPI()
    ae.APPID = credentials.AppID
    ae.APPSECRET = credentials.AppSecret
    #systems = await ae.get_ess_list()
    #print(systems)
    day = '2023-03-02'
    one_date_power = await ae.get_one_date_power_by_sn(credentials.SystemSN, day)
    one_date_power.sort(key=lambda e:e['uploadTime'])
    #print('\n'.join(map(repr, (e for e in one_date_power))))
    one_date_energy = await ae.get_one_date_energy_by_sn(credentials.SystemSN, day)
    print('\n'.join(map(repr, (e for e in one_date_energy.items()))))
    epvs = [e2['ppv'] * delta_seconds(e1, e2)/60/60/1000 for e1, e2 in zip(one_date_power[:-1],one_date_power[1:])]
    print('sum(epvs) = ', sum(epvs))

if __name__ == '__main__':
    asyncio.run(compareepv())
```
The output of that script is as follows:
```
('sysSn', 'AL#########')
('theDate', '2023-03-02')
('eCharge', 4.9)
('epv', 19.3)
('eOutput', 9.6)
('eInput', 0.0)
('eGridCharge', 0.0)
('eDischarge', 6.5)
('eChargingPile', 0.0)
sum(epvs) =  18.914101111111098
```
Note how the `sum(epvs)` doesn't match the `epv = 19.3` value?

Assumptions I made:

 * The `ppv` entries from the `ae.get_one_date_power_by_sn()` return value is an average over the measurement time period
 * The measurement time period is the difference between the previous and current `uploadTime` entries of the `ae.get_one_date_power_by_sn()` return value.

I think at least one of my assumptions must be wrong or the difference in value (about 2%) is a measurement error. Which one is it?

**Comment by ElevenFan** [comment]
@chrisgeli This is real-time data.

**Comment by chrisgeli** [comment]
Sorry for the confusion, @ElevenFan - I should have left out the definition of `async def monitor()` which is actually not used by the script. I have now removed it to avoid further confusion.

The discrepancy is between the data provided by the `get_one_date_power_by_sn` and `get_one_date_energy_by_sn` functions, which are, as far as I understand, recorded in the https://openapi.alphaess.com/ database.

I am imagining that somehow, the output of `get_one_date_energy_by_sn` gets calculated from the real-time data generated by the system, which gets recorded and is accessible via `get_one_date_power_by_sn`, or are these completely separate systems? If so, how are the results of `get_one_date_energy_by_sn` get calculated?

**Comment by RizzoRat** [comment]
Both data types are polled from the meter via modbus.
let's say this is done once every 30 minutes (it is not, but then you get the idea why energy and power data  must differ).
The power in Watts is a current value (current in the sense of currently, not power current), the wattage flowing the very moment you look at it. However, you will have no idea about the power flows between two measurements. Apparently, the system calculates an average and stores it every 5 minutes for the power graph. It does NOT properly integrate over time.

Energy, on the other hand, is the counter of the meter in Wh. The meter is built to integrate power over time to measure energy very accurately.
If you consume like 2kWh in an hour, it doesnt not matter if you read 1, 2, 5 or 60 times during that hour, you won't miss anything - after an hour the counter will show the same value. But if you take only 1,2,5 or 60 times a sample of currently flowing power and multiply that with the time that can only be an approximation (the more often you take a sample, the more accureate of course). Already a modbus transfers take enough time to make it pretty inaccurate, though.

Hence, power data is an average from sampled, basically unreliable data you Shpuld not multiply with time, because by the nature of the measurement, it must be inaccurate.

**Comment by ElevenFan** [comment]
@chrisgeli get_one_date_power_by_sn is the data of one day without the power map, please do not compare this data with our power map, our power map has beautified data, not the original data, and get_one_date_energy_by_sn is the calculated energy data, to be precise, It is the last piece of data of the day - the first piece of data of the day.my english is not good。

**Comment by ElevenFan** [comment]
Close
