### ISSUE TITLE
About EV API

### ISSUE THREAD

**Issue by ElevenFan** [alphaess-developer/alphacloud_open_api#24]
We have been notified that we will develop EV-related APIs next. You can remotely enable functions such as charging and discharging of charging piles。

**Comment by ElevenFan** [comment]
@LukasFoukal  It is expected to be developed in mid-June，Now Api is still being attacked, this is the biggest problem at present。

**Comment by roggepaul** [comment]
Hi @ElevenFan, I want to make another suggestion for the upcoming EV API:  it would also be nice to check if a EV is connected to a alphaess wallbox via api

**Comment by ElevenFan** [comment]
@roggepaul What does it mean?I will release the Api of the charging pile in one week。

**Comment by roggepaul** [comment]
@ElevenFan sorry for not describing it enough. When I manually start the charging of an electric vehicle via tha app I use the tab where I can press the button "start" and "stopp" at the bottom. At the top of this app view it shows if an electric vehicle is currently connected to the wallbox (so if in my case a IEC 62196 Typ 2 is plugged in the charging port of the electric vehicle) or not. for my automation this information is necessary because I only want/should start the charging over the alphaess wallbox if it is connected to an electric vehicle.

![information if EV is connected to wallbox](https://github.com/alphaess-developer/alphacloud_open_api/assets/95296045/d0724b97-665f-4c3c-bc74-69e28c00a6db)
(german "nicht angeschlossen" -> english "not connected")

**Comment by ElevenFan** [comment]
@roggepaul We are about to add a new one, and it will be updated next week, and you can test it together

**Comment by ElevenFan** [comment]
@LukasFoukal I will update online document。

**Comment by ElevenFan** [comment]
@LukasFoukal @roggepaul The charging pile API has been updated

**Comment by roggepaul** [comment]
Hi @LukasFoukal, thank you for developing a new API for charging EVs. I had a look on the new endpoints and I could automate everything I want with the given APIs. unfortunatly, I ran into an issue: I used the getEvChargerStatusBySn endpoint to obtain the charging pile status. The API returns 1 (Available), which means that an EV is connected to the Wallbox and the charging could start (right?) but in the app it shows, that the EV is not connected to the wallbox (which would be state 4 or 5).
so there seems to be a difference between the status shown in the app and the status returned by the API.

btw: what is the difference between the status SuspendedEVSE and SuspendedEV?

**Comment by ElevenFan** [comment]
@roggepaul I check document，our translation sucks

**Comment by ElevenFan** [comment]
@roggepaul Do you have SLACK, you can send me a mail, I will add you

**Comment by roggepaul** [comment]
@ElevenFan sure, please add rogge.paul1@gmail.com / rogge.paul1@gmail.com.  I will delete this message when you added me. thank you

**Comment by LukasFoukal** [comment]
What is the household current setting in the API? Is that the thing that is at the top of the app and only accepts values between 32 and 1000? I would like to set the charge current labeled: "Charging Current Setting (A/phase)".

What even is the household setup? I thought your installer set it up, but I want to change the charge current to the car based on the PV power and battery SoC

**Comment by LukasFoukal** [comment]
So where are you at with this? Any chance the charge current will get added?
