### ISSUE TITLE
no response from openapi.alphaess.com

### ISSUE THREAD

**Issue by ajhurst** [alphaess-developer/alphacloud_open_api#57]
MY AlphaESS code has stopped running at 0:00, 1 Jan 2024 UTC.  Has something been reset that I don't know about?

ping openapi.alphaess.com gives no response, and the error message I get is
"aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host openapi.alphaess.com:443 ssl:default [Connection reset by peer]"

Any insights gratefully received!

**Comment by RizzoRat** [comment]
Well, from the date and time, the backend seems to be crashed at years' change. Logging into their standard cloud also fails with a timeout, so all users and mobile apps do not work We'll need to wait until they fix it

**Comment by wmachiel** [comment]
Same issue here...
Thx for the information

**Comment by ness111** [comment]
I also had no connection to my SMILE-T10-HV-INV with the openapi adapter since 0:00, 1 Jan 2024 UTC:
Iobroker protocol:
•	info starting. Version 2.0.0 in /…/iobroker.alpha-ess, node: v18.17.1, js-controller: 5.0.17
•	Error performing get request getLastPowerData?sysSn=Axxxxxxxxxxxxx: AxiosError: timeout of 10000ms exceeded
•	unknown error occurred: null (#1) Group:Realtime

Thank you for any help.

**Comment by Poshy163** [comment]
Yep, asked in the slack channel and allegedly this is the issue.

You would of thought it would be a priority to fix....

<img width="412" alt="Screenshot 2024-01-01 at 12 18 46 pm" src="https://github.com/alphaess-developer/alphacloud_open_api/assets/53972874/d8fa2fb0-d6dc-4edb-836d-fe944b198925">

**Comment by ajhurst** [comment]
Seems to have recovered now.  API code now working again.  Thanks to whoever was responsible!

**Comment by Gaspode69** [comment]
@philosifer 
See https://github.com/alphaess-developer/alphacloud_open_api/issues/59
